import qrcode from "./vendor/qrcode.mjs";
const CONFIG=window.APP_CONFIG??{};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const escapeHtml=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function getReservation(token){const response=await fetch(`${CONFIG.supabaseUrl}/rest/v1/rpc/get_reservation`,{method:"POST",headers:{apikey:CONFIG.supabasePublishableKey,Authorization:`Bearer ${CONFIG.supabasePublishableKey}`,"Content-Type":"application/json"},body:JSON.stringify({p_access_token:token})});if(!response.ok)throw new Error("reservation_not_found");return response.json()}
function qrSvg(token){const qr=qrcode(0,"M");qr.addData(`${location.origin}/checkin.html?t=${token}`,"Byte");qr.make();return qr.createSvgTag({cellSize:5,margin:3,scalable:true})}
function ticketCard(item,reservation){const paid=reservation.payment_status==="paid";return `<article class="ticket"><div class="ticket-brand"><img src="./assets/iba-symbol.png" alt=""><span>Festa da Virada<small>1º de janeiro de 2027 · 00h20</small></span></div><div class="ticket-main"><div><p>PARTICIPANTE</p><h2>${escapeHtml(item.name)}</h2><dl><div><dt>Cadeira</dt><dd>${escapeHtml(item.code??"Sem cadeira")}</dd></div><div><dt>Categoria</dt><dd>${escapeHtml(item.category==="full"?"Inteira":item.category==="half"?"Meia":"Gratuita")}</dd></div><div><dt>Protocolo</dt><dd>${escapeHtml(reservation.protocol)}</dd></div></dl></div><div class="qr">${qrSvg(item.ticket_token)}</div></div><footer class="${paid?"paid":"pending"}"><strong>${paid?"ENTRADA LIBERADA":"SALDO PENDENTE"}</strong><span>${paid?"Pagamento quitado":"Quitação necessária para entrar"}</span></footer></article>`}
async function init(){const token=location.hash.slice(1)||JSON.parse(localStorage.getItem("fv26_reservation_access")||"null")?.accessToken;try{if(!token)throw new Error();const r=await getReservation(token);if(!["partial","paid"].includes(r.payment_status))throw new Error("not_released");document.getElementById("title").textContent=`Protocolo ${r.protocol}`;document.getElementById("reservation-summary").textContent=`Pago: ${money.format(r.paid_amount)} · Saldo: ${money.format(r.balance_amount)}`;document.getElementById("message").textContent=r.payment_status==="paid"?"Apresente os QR Codes na entrada.":"Os ingressos foram gerados, mas a entrada só será liberada após a quitação do saldo.";const items=[...(r.seats??[]),...(r.free_children??[])].filter(i=>i.item_status==="active");document.getElementById("tickets").innerHTML=items.map(i=>ticketCard(i,r)).join("");}catch(e){document.getElementById("title").textContent="Ingressos indisponíveis";const el=document.getElementById("error");el.hidden=false;el.textContent=e.message==="not_released"?"Os ingressos serão liberados após a aprovação de pelo menos 30% do pagamento.":"Não foi possível abrir esta inscrição neste navegador.";}}
document.getElementById("print-button").addEventListener("click",()=>window.print());init();
